#!/usr/bin/env bash
# display information about subdomains.

func () {
	if [ "$#" -eq 2 ]; then
		dig $2.$1 | grep -A1 'ANSWER SECTION:' | tr '\n' ' ' | awk '{split($0, elem, " "); split(elem[4], sub_elem, "."); printf "The subdomain %s is a %s record and points to %s\n",sub_elem[1], elem[7], elem[8]}'
	elif [ $# -eq 1 ]; then
		dig www.$1 | grep -A1 'ANSWER SECTION:' | tr '\n' ' ' | awk '{split($0, elem, " "); printf "The subdomain www is a %s record and points to %s\n",elem[7], elem[8]}'
		dig lb-01.$1 | grep -A1 'ANSWER SECTION:' | tr '\n' ' ' | awk '{split($0, elem, " "); printf "The subdomain lb-01 is a %s record and points to %s\n",elem[7], elem[8]}'
		dig web-01.$1 | grep -A1 'ANSWER SECTION:' | tr '\n' ' ' | awk '{split($0, elem, " "); printf "The subdomain web-01 is a %s record and points to %s\n",elem[7], elem[8]}'
		dig web-02.$1 | grep -A1 'ANSWER SECTION:' | tr '\n' ' ' | awk '{split($0, elem, " "); printf "The subdomain web-02 is a %s record and points to %s\n",elem[7], elem[8]}'
	fi
}

func $1 $2
