#!/usr/bin/env bash
# configures a server on port 80 of all the servers active
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
