#!/usr/bin/env bash
# Run Nginx as Nginx
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sudo sed -i '/pid /run/nginx.pid;/a user nginx' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
